# Generated by Django 4.2.6 on 2024-01-10 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_orderwordsexercise_wordpiece'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='type',
            field=models.CharField(choices=[('arrange', 'arrange'), ('', '')], default='', max_length=30),
        ),
    ]
