# Generated by Django 4.2.6 on 2024-01-11 13:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('learning', '0003_exercise_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='completed_by',
            field=models.ManyToManyField(blank=True, related_name='completed_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
