# Generated by Django 4.2.6 on 2024-04-26 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0005_answerexercise_chooserightanswer_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CompleteSentenceExercise',
            new_name='CompleteExercise',
        ),
        migrations.AddField(
            model_name='answerchoice',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
    ]
