# Generated by Django 4.2.6 on 2024-04-27 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0006_rename_completesentenceexercise_completeexercise_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='type',
            field=models.CharField(choices=[], default='', editable=False, max_length=30),
        ),
    ]
