# Generated by Django 4.2.6 on 2024-05-23 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0008_lesson_description_alter_lesson_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderwordsexercise',
            name='query',
            field=models.CharField(default='Put the words in order', max_length=60),
        ),
    ]
