# Generated by Django 4.2.6 on 2024-05-23 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0009_orderwordsexercise_query'),
    ]

    operations = [
        migrations.AddField(
            model_name='completeexercise',
            name='query',
            field=models.CharField(default='Complete the sentence', max_length=60),
        ),
        migrations.AddField(
            model_name='joinwordsexercise',
            name='query',
            field=models.CharField(default='Match the pairs', max_length=60),
        ),
    ]
