# Generated by Django 4.2.6 on 2024-08-17 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0011_exercise_order_lesson_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipText',
            fields=[
                ('exercise_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='learning.exercise')),
                ('text', models.TextField()),
            ],
            bases=('learning.exercise',),
        ),
        migrations.CreateModel(
            name='WordFlashcard',
            fields=[
                ('exercise_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='learning.exercise')),
                ('original_word', models.CharField(max_length=100)),
                ('translated_word', models.CharField(max_length=100)),
            ],
            bases=('learning.exercise',),
        ),
        migrations.AddField(
            model_name='exercise',
            name='audio',
            field=models.FileField(null=True, upload_to='exercises_audios'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='image',
            field=models.ImageField(null=True, upload_to='exercises_images'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='scored',
            field=models.BooleanField(default=True),
        ),
    ]
