# Generated by Django 4.2.6 on 2024-08-17 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0012_tiptext_wordflashcard_exercise_audio_exercise_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='exercises_audios'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='exercises_images'),
        ),
    ]
