# Generated by Django 4.2.6 on 2024-10-05 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0013_alter_exercise_audio_alter_exercise_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completeexercise',
            name='query',
            field=models.CharField(default='Complete the sentence', max_length=120),
        ),
    ]
